bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userLogin
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userSignup
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userProfileGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userProfileUpdate
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic currenciesGetAll
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic searchUsers
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userInvitationsGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupCreate
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupDetailsUpdate
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupAcceptInvitation
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupDeclineInvitation
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupProfileGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic searchGroups
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupAddExpense
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userSettleUpList
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userSettleUp
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupBalancesGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupDebtsGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupExpensesGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userRecentActivityGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic addCommentsExpense
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic deleteCommentsExpense
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userDebtsGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic userDashboardBalanceGet
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic groupLeave
bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic response_topic