export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const SET_ERROR = "SET_ERROR";
export const SET_MESSAGE = "SET_MESSAGE";
// CREATE GROUP
export const CREATE_GROUP = "CREATE_GROUP";
export const SET_ERROR_GROUP_INFO = "SET_ERROR_GROUP_INFO";
// EDIT GROUP
export const EDIT_GROUP = "EDIT_GROUP";
export const SET_ERROR_EDIT_GROUP = "SET_ERROR_EDIT_GROUP";
// GROUP DETAILS
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_GROUP_DETAILS = "GET_GROUP_DETAILS";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const SET_ERROR_ADD_COMMENT = "SET_ERROR_ADD_COMMENT";
// RECENT ACTIVITY
export const GET_RECENT_ACTIVITY = "RECENT_ACTIVITY";
// GET DASHBOARD BALANCE
export const GET_DASHBOARD_BALANCE = "GET_DASHBOARD_BALANCE";
// SETTLE UP
export const SETTLE_UP = "SETTLE_UP";
